services:
  minio:
    image: minio/minio:RELEASE.2024-08-29T01-40-52Z
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL}
    volumes:
      - n2devskill-minio:/data
    command: server --console-address ":9001" /data
    networks:
      - n2devskill
  nginx:
    image: nginx:1.27.0
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    env_file:
      - .env
    environment:
      MINIO_SERVER_NAME: ${MINIO_SERVER_NAME}
    networks:
      - n2devskill
volumes:
  n2devskill-minio:
networks:
  n2devskill:
    external: true
    name: n2devskill
